# 1. for git repos use the 'git+https'
# 2. for local files leave scheme bare or use 'file' scheme

# if the files in the repo are not at the top-level use the 'fragment'
# section (after the #) for the path within the repo
upstream_url = "git+https://github.com/{{cookiecutter.owner_nickname}}/{{cookiecutter.project_slug}}.git"

[taskset]

dirname = "tasks"

